// <auto-generated />
using System;
using GamaEdtech.Backend.Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamaEdtech.Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250131130200_SubjectTopic")]
    partial class SubjectTopic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamaEdtech.Backend.Common.DataAccess.Audit.Audit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("Date");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("IpAddress");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("UserAgent");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("UserId");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.DataAccess.Audit.AuditEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .HasColumnName("Id");

                    b.Property<string>("AuditId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .HasColumnName("AuditId");

                    b.Property<byte>("AuditType")
                        .HasColumnType("tinyint")
                        .HasColumnName("AuditType");

                    b.Property<int>("EntityType")
                        .HasColumnType("int")
                        .HasColumnName("EntityType");

                    b.Property<string>("IdentifierId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("IdentifierId");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.DataAccess.Audit.AuditEntryProperty", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(26)")
                        .HasColumnName("Id");

                    b.Property<string>("AuditEntryId")
                        .IsRequired()
                        .HasColumnType("char(26)")
                        .HasColumnName("AuditEntryId");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NewValue");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OldValue");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("PropertyName");

                    b.HasKey("Id");

                    b.HasIndex("AuditEntryId");

                    b.ToTable("AuditEntryProperties");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Identity.DataProtection.DataProtectionKey", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(26)")
                        .HasColumnName("Id");

                    b.Property<string>("FriendlyName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("FriendlyName");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Xml");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.ApplicationSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreationDate");

                    b.Property<int>("CreationUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreationUserId");

                    b.Property<DateTimeOffset?>("LastModifyDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastModifyDate");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastModifyUserId");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("ApplicationSettings");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreationDate");

                    b.Property<int>("CreationUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreationUserId");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Icon");

                    b.Property<DateTimeOffset?>("LastModifyDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastModifyDate");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastModifyUserId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("int")
                        .HasColumnName("BoardId");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreationDate");

                    b.Property<int>("CreationUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreationUserId");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Description");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Icon");

                    b.Property<DateTimeOffset?>("LastModifyDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastModifyDate");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastModifyUserId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar")
                        .HasColumnName("NormalizedName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_ApplicationRole_NormalizedName")
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("ApplicationRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "85465B3B-E646-49BC-AAC6-D07C450B3AE3",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar")
                        .HasColumnName("ClaimType");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ClaimValue");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ApplicationRoleClaims");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("EmailConfirmed");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit")
                        .HasColumnName("Enabled");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar")
                        .HasColumnName("NormalizedEmail");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar")
                        .HasColumnName("NormalizedUserName");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar")
                        .HasColumnName("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("PhoneNumberConfirmed");

                    b.Property<DateTimeOffset?>("RegistrationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("RegistrationDate");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_ApplicationUser_NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("IX_ApplicationUser_NormalizedUserName")
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("ApplicationUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5BABA139-4AE5-4C47-BC65-DE4849346A17",
                            Email = "admin@gamaedtech.com",
                            EmailConfirmed = true,
                            Enabled = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GAMAEDTECH.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEMLN3xqYWUja6ShSK0teeCYzziU6b+KghL4AiSXrb03Y3VbBfxKP7LUF3PZAJhQJ+Q==",
                            PhoneNumber = "09355028981",
                            PhoneNumberConfirmed = true,
                            RegistrationDate = new DateTimeOffset(new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            SecurityStamp = "EAF1FA85-3DA1-4A40-90C6-65B97BF903F1",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar")
                        .HasColumnName("ClaimType");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ClaimValue");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ApplicationUserClaim_UserId");

                    b.ToTable("ApplicationUserClaims");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar")
                        .HasColumnName("LoginProvider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ProviderKey");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar")
                        .HasColumnName("ProviderDisplayName");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ApplicationUserLogin_UserId");

                    b.ToTable("ApplicationUserLogins");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_ApplicationUserRole_RoleId");

                    b.ToTable("ApplicationUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar")
                        .HasColumnName("LoginProvider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.Property<string>("Value")
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("ApplicationUserTokens");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("Code");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreationDate");

                    b.Property<int>("CreationUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreationUserId");

                    b.Property<DateTimeOffset?>("LastModifyDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastModifyDate");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastModifyUserId");

                    b.Property<byte>("LocationType")
                        .HasColumnType("tinyint")
                        .HasColumnName("Type");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreationUserId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("LocationType");

                    b.HasIndex("ParentId");

                    b.HasIndex("Title", "LocationType", "ParentId")
                        .IsUnique()
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Address");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreationDate");

                    b.Property<int>("CreationUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreationUserId");

                    b.Property<DateTimeOffset?>("LastModifyDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastModifyDate");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastModifyUserId");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("LocalName");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.Property<byte>("SchoolType")
                        .HasColumnType("tinyint")
                        .HasColumnName("Type");

                    b.Property<int>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("StateId");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("LastModifyUserId");

                    b.HasIndex("StateId");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreationDate");

                    b.Property<int>("CreationUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreationUserId");

                    b.Property<DateTimeOffset?>("LastModifyDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastModifyDate");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastModifyUserId");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreationDate");

                    b.Property<int>("CreationUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreationUserId");

                    b.Property<DateTimeOffset?>("LastModifyDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastModifyDate");

                    b.Property<int?>("LastModifyUserId")
                        .HasColumnType("int")
                        .HasColumnName("LastModifyUserId");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("Order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("CreationUserId");

                    b.HasIndex("LastModifyUserId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("SubjectGrades", b =>
                {
                    b.Property<int>("GradesId")
                        .HasColumnType("int")
                        .HasColumnName("GradeId");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.HasKey("GradesId", "SubjectsId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("SubjectGrades");
                });

            modelBuilder.Entity("SubjectTopics", b =>
                {
                    b.Property<int>("SubjectsId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectId");

                    b.Property<int>("TopicsId")
                        .HasColumnType("int")
                        .HasColumnName("TopicId");

                    b.HasKey("SubjectsId", "TopicsId");

                    b.HasIndex("TopicsId");

                    b.ToTable("SubjectTopics");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.DataAccess.Audit.AuditEntry", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.DataAccess.Audit.Audit", "Audit")
                        .WithMany("AuditEntries")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.DataAccess.Audit.AuditEntryProperty", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.DataAccess.Audit.AuditEntry", "AuditEntry")
                        .WithMany("AuditEntryProperties")
                        .HasForeignKey("AuditEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEntry");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.ApplicationSettings", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreationUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Board", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreationUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Grade", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Board");

                    b.Navigation("CreationUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationRoleClaim", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUserClaim", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUserLogin", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUserToken", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Location", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Location", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("CreationUser");

                    b.Navigation("LastModifyUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.School", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Location", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreationUser");

                    b.Navigation("LastModifyUser");

                    b.Navigation("State");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Subject", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreationUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Topic", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "CreationUser")
                        .WithMany()
                        .HasForeignKey("CreationUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", "LastModifyUser")
                        .WithMany()
                        .HasForeignKey("LastModifyUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreationUser");

                    b.Navigation("LastModifyUser");
                });

            modelBuilder.Entity("SubjectGrades", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Grade", null)
                        .WithMany()
                        .HasForeignKey("GradesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SubjectTopics", b =>
                {
                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamaEdtech.Backend.Common.Data.Entity.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.DataAccess.Audit.Audit", b =>
                {
                    b.Navigation("AuditEntries");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.DataAccess.Audit.AuditEntry", b =>
                {
                    b.Navigation("AuditEntryProperties");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationRole", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GamaEdtech.Backend.Common.Data.Entity.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserClaims");

                    b.Navigation("UserLogins");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
